version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy:/etc/caddy
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory

  trojan-go:
    image: p4gefau1t/trojan-go
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./trojan-go:/etc/trojan-go
      - ./ssl:/ssl
    depends_on:
      - caddy
